import pygame


class SETTINGS:

    FPS = 120
    DISPLAY_FLAGS = pygame.FULLSCREEN | pygame.HWACCEL

    SCALE = 240  # pixels / meter
    HANDLE_HIGHLIGHT = 2


class COLORS:

    BACKGROUND = 20, 20, 20
    FIELD = 0, 0, 0
    MASS = 160, 0, 0
    RAIL = 60, 60, 60
    HANDLE_INACTIVE = 0, 150, 0
    HANDLE_ACTIVE = 0, 200, 0
    REFERENCE = 60, 60, 60

    RED_PLOT = 200, 0, 0
    GREEN_PLOT = 0, 180, 0
    BLUE_PLOT = 100, 100, 250
    YELLOW_PLOT = 200, 200, 0

    LABEL = 160, 160, 160
    TUNER = ((100, 100, 100), (120, 120, 120)), ((150, 0, 0), (200, 50, 50))
    SETTING = ((100, 100, 100), (120, 120, 120)), ((70, 70, 220), (80, 80, 250))
    TOP_PLOTTER = FIELD, RAIL, GREEN_PLOT, RED_PLOT
    BOT_PLOTTER = FIELD, RAIL, BLUE_PLOT, YELLOW_PLOT


class LAYOUT:

    WINDOW_WIDTH = 1920
    WINDOW_HEIGHT = 1080
    GAP = 20

    FIELD_SIZE = 850

    LEFT_FIELD = GAP, GAP, FIELD_SIZE, FIELD_SIZE
    RIGHT_FIELD = FIELD_SIZE + GAP * 2, GAP, WINDOW_WIDTH - FIELD_SIZE - GAP * 3, FIELD_SIZE
    BOTTOM_FIELD = GAP, FIELD_SIZE + GAP * 2, WINDOW_WIDTH - GAP * 2, WINDOW_HEIGHT - FIELD_SIZE - GAP * 3

    SYSTEM_CENTER = FIELD_SIZE / 2 + GAP, FIELD_SIZE / 2 + GAP

    CONTROLLER_TEXT = BOTTOM_FIELD[0] + GAP, BOTTOM_FIELD[1] + GAP
    CONTROLLER_LEFT = 180
    KP_TUNER = BOTTOM_FIELD[0] + GAP, WINDOW_HEIGHT - GAP * 2 - 60
    KI_TUNER = BOTTOM_FIELD[0] + GAP, WINDOW_HEIGHT - GAP * 2 - 30
    KD_TUNER = BOTTOM_FIELD[0] + GAP, WINDOW_HEIGHT - GAP * 2
    AW_SWITCH = BOTTOM_FIELD[0] + GAP + CONTROLLER_LEFT, WINDOW_HEIGHT - GAP * 2 - 30
    ND_TUNER = BOTTOM_FIELD[0] + GAP + CONTROLLER_LEFT, WINDOW_HEIGHT - GAP * 2

    ACTUATOR_LEFT = CONTROLLER_LEFT + 260
    ACTUATOR_TEXT = BOTTOM_FIELD[0] + GAP + ACTUATOR_LEFT, BOTTOM_FIELD[1] + GAP
    ACT_DELAY = GAP * 2 + ACTUATOR_LEFT, WINDOW_HEIGHT - GAP * 2 - 30
    ACT_LIMIT = GAP * 2 + ACTUATOR_LEFT, WINDOW_HEIGHT - GAP * 2 - 60

    NOISE_LEFT = ACTUATOR_LEFT + 260
    SENSOR_TEXT = BOTTOM_FIELD[0] + GAP + NOISE_LEFT, BOTTOM_FIELD[1] + GAP
    SENSOR_DELAY = GAP * 2 + NOISE_LEFT, WINDOW_HEIGHT - GAP * 2 - 30
    SENSOR_NOISE = GAP * 2 + NOISE_LEFT, WINDOW_HEIGHT - GAP * 2 - 60

    PLOT_WIDTH, PLOT_HEIGHT = RIGHT_FIELD[2] - GAP * 2, (RIGHT_FIELD[3] - GAP * 3) / 2

    TOP_PLOT = RIGHT_FIELD[0] + GAP, RIGHT_FIELD[1] + GAP, PLOT_WIDTH, PLOT_HEIGHT
    BOT_PLOT = RIGHT_FIELD[0] + GAP, TOP_PLOT[1] + TOP_PLOT[3] + GAP, PLOT_WIDTH, PLOT_HEIGHT


class SYSTEM:

    MASS = 0.5
    DAMPING = 0.5
    MAX_TORQUE = 1
    G = 9.81

    MASS_WIDTH = 0.4
    MASS_HEIGHT = 0.2
    RAIL_LENGTH = 3
    RAIL_WIDTH = 0.02

    HANDLE_SIZE = 0.04

    KP = 0
    KI = 0
    KD = 0