import pygame


class SETTINGS:

    FPS = 120
    DISPLAY_FLAGS = pygame.FULLSCREEN | pygame.HWACCEL

    SCALE = 240  # pixels / meter
    HANDLE_HIGHLIGHT = 2


class COLORS:

    BACKGROUND = 10, 10, 10
    FIELD = 0, 0, 0
    MASS = 160, 0, 0
    RAIL = 60, 60, 60
    HANDLE_INACTIVE = 0, 150, 0
    HANDLE_ACTIVE = 0, 200, 0
    REFERENCE = 60, 60, 60

    LABEL = 140, 140, 140
    TUNER = ((100, 100, 100), (120, 120, 120)), ((150, 0, 0), (200, 50, 50))
    SETTING = ((100, 100, 100), (120, 120, 120)), ((70, 70, 220), (80, 80, 250))
    PLOTTER = BACKGROUND, LABEL, HANDLE_INACTIVE, MASS


class LAYOUT:

    WINDOW_WIDTH = 1920
    WINDOW_HEIGHT = 1080
    GAP = 20

    FIELD_SIZE = 850

    LEFT_FIELD = GAP, GAP, FIELD_SIZE, FIELD_SIZE
    RIGHT_FIELD = FIELD_SIZE + GAP * 2, GAP, WINDOW_WIDTH - FIELD_SIZE - GAP * 3, FIELD_SIZE
    BOTTOM_FIELD = GAP, FIELD_SIZE + GAP * 2, WINDOW_WIDTH - GAP * 2, WINDOW_HEIGHT - FIELD_SIZE - GAP * 3

    SYSTEM_CENTER = FIELD_SIZE / 2 + GAP, FIELD_SIZE / 2 + GAP

    CONTROLLER_TEXT = BOTTOM_FIELD[0] + GAP, BOTTOM_FIELD[1] + GAP
    KP_TUNER = BOTTOM_FIELD[0] + GAP, WINDOW_HEIGHT - GAP * 2 - 60
    KI_TUNER = BOTTOM_FIELD[0] + GAP, WINDOW_HEIGHT - GAP * 2 - 30
    KD_TUNER = BOTTOM_FIELD[0] + GAP, WINDOW_HEIGHT - GAP * 2

    ACTUATOR_LEFT = 200
    ACTUATOR_TEXT = BOTTOM_FIELD[0] + GAP + ACTUATOR_LEFT, BOTTOM_FIELD[1] + GAP
    ACT_DELAY = GAP * 2 + ACTUATOR_LEFT, WINDOW_HEIGHT - GAP * 2
    ACT_LIMIT = GAP * 2 + ACTUATOR_LEFT, WINDOW_HEIGHT - GAP * 2 - 30

    NOISE_LEFT = 440
    SENSOR_TEXT = BOTTOM_FIELD[0] + GAP + NOISE_LEFT, BOTTOM_FIELD[1] + GAP
    SENSOR_DELAY = GAP * 2 + NOISE_LEFT, WINDOW_HEIGHT - GAP * 2
    SENSOR_NOISE = GAP * 2 + NOISE_LEFT, WINDOW_HEIGHT - GAP * 2 - 30

    TOP_PLOT = RIGHT_FIELD[0] + GAP, RIGHT_FIELD[1] + GAP, RIGHT_FIELD[2] - GAP * 2, (RIGHT_FIELD[3] - GAP * 4) / 3


class SYSTEM:

    MASS = 0.5
    DAMPING = 0.5
    MAX_TORQUE = 1
    G = 9.81

    MASS_WIDTH = 0.4
    MASS_HEIGHT = 0.2
    RAIL_LENGTH = 3
    RAIL_WIDTH = 0.02

    HANDLE_SIZE = 0.04

    KP = 0
    KI = 0
    KD = 0